// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'banner': string;
  'bannerHeight': string;
  'bannerWidth': string;
  'gridBaseline': string;
  'monoGreyA100': string;
  'monoGreyLight': string;
  'monoWhiteA50': string;
}
export const cssExports: CssExports;
export default cssExports;
