// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorBlue': string;
  'colorPurpleLight': string;
  'container': string;
  'content': string;
  'cross': string;
  'gridBaseline': string;
  'monoBlackA250': string;
  'monoWhite': string;
  'monoWhiteA200': string;
  'monoWhiteA50': string;
  'shortBar': string;
  'subTitle': string;
  'withBottomShadow': string;
}
export const cssExports: CssExports;
export default cssExports;
