// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'baseButton': string;
  'circle': string;
  'colorBlue': string;
  'colorBlueA250': string;
  'colorBlueA400': string;
  'ghost': string;
  'gridBaseline': string;
  'heightLarge': string;
  'heightMedium': string;
  'large': string;
  'medium': string;
  'monoWhite': string;
  'primary': string;
  'rippleContainer': string;
  'text': string;
  'textSmall': string;
  'withIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
