// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'baseButton': string;
  'circle': string;
  'gridBaseline': string;
  'iconButton': string;
  'large': string;
  'lengthLarge': string;
  'lengthSmall': string;
  'small': string;
}
export const cssExports: CssExports;
export default cssExports;
