// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authorContainer': string;
  'authorMarginLeft': string;
  'avatarImg': string;
  'colorBlueUltraLight': string;
  'colorPurpleLight': string;
  'content': string;
  'email': string;
  'gridBaseline': string;
  'monoGreyA200': string;
  'monoGreyLight': string;
  'monoWhite': string;
  'monoWhiteA50': string;
  'name': string;
  'nav': string;
  'sourceCodeBanner': string;
  'sourceCodeBannerHeight': string;
  'sourceCodeBannerWidth': string;
}
export const cssExports: CssExports;
export default cssExports;
