// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blogAbstract': string;
  'blogList': string;
  'gridBaseline': string;
  'home': string;
  'monoGreyLight': string;
}
export const cssExports: CssExports;
export default cssExports;
