// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'animationTransition': string;
  'gridBaseline': string;
  'hideMenu': string;
  'mainContent': string;
  'nav': string;
  'navWidth': string;
}
export const cssExports: CssExports;
export default cssExports;
