// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'colorBlue': string;
  'gridBaseline': string;
  'monoWhite': string;
  'ripple': string;
  'rippleEffect': string;
  'white': string;
}
export const cssExports: CssExports;
export default cssExports;
