// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blueA400': string;
  'gridBaseline': string;
  'link': string;
  'list': string;
  'monoBlackA100': string;
  'monoBlackA150': string;
  'monoGreyA100': string;
  'monoGreyUltraLight': string;
}
export const cssExports: CssExports;
export default cssExports;
