// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colorBlue': string;
  'title': string;
  'underline': string;
}
export const cssExports: CssExports;
export default cssExports;
