// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'content': string;
  'gridBaseline': string;
  'monoGreyA100': string;
  'time': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
