// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'gridBaseline': string;
  'monoWhite': string;
  'ripple': string;
  'rippleEffect': string;
  'useAnimation': string;
}
export const cssExports: CssExports;
export default cssExports;
