// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'base': string;
  'defaultFontStack': string;
  'fontSizeMedium': string;
  'fontSizeMicro': string;
  'fontSizeTitleLarge': string;
  'fontSizeTitleMedium': string;
  'fontSizeTitleSmall': string;
  'fontWeightBold': string;
  'fontWeightRegular': string;
  'fontWeightSemiBold': string;
  'textBase': string;
  'textMedium': string;
  'textMediumLineHeight': string;
  'textMicro': string;
  'textMicroLineHeight': string;
  'textTitleLargeLineHeight': string;
  'textTitleMediumLineHeight': string;
  'textTitleSmallLineHeight': string;
  'titleBase': string;
  'titleLarge': string;
  'titleMedium': string;
  'titleSmall': string;
}
export const cssExports: CssExports;
export default cssExports;
