// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatarImg': string;
  'colorBlueUltraLight': string;
  'colorPurpleLight': string;
  'container': string;
  'email': string;
  'gridBaseline': string;
  'marginLeft': string;
  'monoWhite': string;
  'name': string;
}
export const cssExports: CssExports;
export default cssExports;
