name: backends
on:
  push:
    paths:
      - packages/backends/**
      - .github/workflows/backends.yml
jobs:
  install:
    name: install node_modules
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v1
        with:
          lfs: true
      - id: yarn-cache
        name: Fetch node modules
        uses: actions/cache@v1
        with:
          key: "${{ runner.os }}-yarn-${{ hashFiles('yarn-lock.json') }}"
          path: node_modules
      - id: yarn-install
        if: steps.yarn-install.outputs.cache-hit != 'true'
        name: Install node modules
        run: yarn install --frozen-lockfile

  build:
    name: build nest
    runs-on: ubuntu-latest
    needs: install
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v1
        with:
          lfs: true
      - id: yarn-cache
        name: Fetch node modules
        uses: actions/cache@v1
        with:
          key: "${{ runner.os }}-yarn-${{ hashFiles('yarn-lock.json') }}"
          path: node_modules
      - uses: actions/github-script@v3
        if: steps.yarn-install.outputs.cache-hit != 'true'
        with:
          script: |
            core.setFailed('node_modules can not be found')
      - id: nest-build
        name: Run nest build
        run: yarn build
        working-directory: packages/backends
