name: backends
on:
  push:
    paths:
      - packages/backends/**
      - .github/workflows/backends.yml
jobs:
  build:
    name: build nest
    runs-on: ubuntu-latest
    needs: install
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v1
        with:
          lfs: true
      - id: yarn-cache
        name: Fetch node modules
        uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}"
          restore-keys: "${{ runner.os }}-yarn-"
          path: node_modules
      - id: yarn-install
        name: Install node modules
        run: yarn install --frozen-lockfile
      - id: nest-build
        name: Run nest build
        run: yarn build
        working-directory: packages/backends
