name: web-CI

on: [push]

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run npm ci
        working-directory: web
        run: npm ci
      - name: Check ESLint
        working-directory: web
        run: npm run lint:ts
      - name: Check typescript
        working-directory: web
        run: npm run lint:ts:types
      - name: Check prettier
        working-directory: web
        run: npm run format
      - name: Run Unit test
        working-directory: web
        run: npm run test -- --ci
      - name: Run webpack build
        env:
          CI: true
          DEBUG: "*"
        working-directory: web
        run: npm run build
