name: web-CI

on: [push]

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Find npm Cache
        uses: actions/cache@v1
        with:
          path: web/node_modules
          key: ${{ runner.OS }}-npm-${{ hashFiles('web/package-lock.json') }}
          restore-keys: ${{ runner.OS }}-npm-
      - name: Run npm
        working-directory: web
        run: npm install
      - name: Check ESLint
        working-directory: web
        run: npm run lint:ts
      - name: Check typescript
        working-directory: web
        run: npm run lint:ts:types
      - name: Check prettier
        working-directory: web
        run: npm run format:ts
      - name: webpack build
        env:
          CI: true
        working-directory: web
        run: npm run build
