name: web
on:
  push:
    paths:
      - packages/web/**
      - .github/workflows/web.yml
jobs:
  webpack:
    name: Webpack
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v1
        with:
          lfs: true
      - id: yarn-cache
        name: fetch node modules
        uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}"
          restore-keys: "${{ runner.os }}-yarn-"
          path: |
            node_modules
            packages/*/node_modules
      - id: yarn-install
        name: Install node modules
        run: yarn install --frozen-lockfile
      - id: webpack
        name: Run webpack build
        run: yarn build
        working-directory: packages/web
        env:
          CI: "true"
          DEBUG: webpack_options*
      - id: deploy-to-s3
        name: Deploy to s3
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_REGION: ap-northeast-2
          AWS_S3_BUCKET: github-cd
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_ACCESS_KEY_VALUE }}"
          DEST_DIR: $GITHUB_REPOSITORY/$GITHUB_REF/$GITHUB_SHA/blog
          SOURCE_DIR: packages/web/dist/blog
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: "--acl public-read --delete"
      - id: display-url
        name: Display deployed url
        run: 'curl "https://3zrr015ofi.execute-api.ap-northeast-2.amazonaws.com/default/deploy-github-build-to-s3?name=blog&commitHash=$GITHUB_SHA&url=https://github-cd.s3.ap-northeast-2.amazonaws.com/$GITHUB_REPOSITORY/$GITHUB_REF/$GITHUB_SHA/blog/index.html"'

  storybook:
    name: Storybook
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v1
        with:
          lfs: true
      - id: yarn-cache
        name: fetch node modules
        uses: actions/cache@v2
        with:
          key: "${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}"
          restore-keys: "${{ runner.os }}-yarn-"
          path: |
            node_modules
            packages/*/node_modules
      - id: yarn-install
        name: Install node modules
        run: yarn install --frozen-lockfile
      - id: storybook
        env:
          DEBUG: storybook_config
        name: Run storybook build
        run: "yarn storybook:build"
        working-directory: packages/web
      - id: configure-aws
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_VALUE }}
          aws-region: ap-northeast-2
      - id: percy-storybook
        env:
          PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}"
        name: Run percy on storybook
        run: "yarn percy:storybook"
        working-directory: packages/web
      - id: deploy-to-s3
        name: Deploy to S3
        run: |
          aws s3 sync . s3://github-cd/fa93hws/blog/refs/heads/ci/$GITHUB_REPOSITORY/$GITHUB_REF/$GITHUB_SHA/storybook
        working-directory: packages/web/target/storybook
      - id: display-url
        name: Display deployed url
        run: 'curl "https://3zrr015ofi.execute-api.ap-northeast-2.amazonaws.com/default/deploy-github-build-to-s3?name=storybook&commitHash=$GITHUB_SHA&url=https://github-cd.s3.ap-northeast-2.amazonaws.com/$GITHUB_REPOSITORY/$GITHUB_REF/$GITHUB_SHA/storybook/index.html"'
